config/routes.rb
Rails.application.routes.draw do
  root 'application#index'

  devise_for :users, :controllers => { :omniauth_callbacks => "callbacks" }

  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  get '/cats/most_talented', to: 'cats#most_talented'

  resources :cats do
    resources :comments
  end

  resources :cat_tricks

  resources :tricks

  resources :users, only: [:show]

  get '/cat_indexes', to: 'cats#indexes'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cat.rb
class Cat < ApplicationRecord
  belongs_to :user
  has_many :cat_tricks
  has_many :tricks, through: :cat_tricks
  has_many :comment

  validates :name, presence: true

  def tricks_attributes=(trick_attributes)
      trick_attributes.values.each do |trick_attribute|
        trick = Trick.find_or_create_by(trick_attribute)
        self.tricks << trick unless trick.name.empty?
      end
  end

  def self.most_talented
    joins(:cat_tricks).group(:cat_id).order("count(*) DESC")
  end

  def self.indexes(user)
    user.cats.map{ |cat| cat.id }
  end

end

app/models/cat_trick.rb
class CatTrick < ApplicationRecord
  belongs_to :cat
  belongs_to :trick
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :cat

  validates :body, presence: true
end

app/models/trick.rb
class Trick < ApplicationRecord
  has_many :cat_tricks
  has_many :cats, through: :cat_tricks

  validates :name, presence: true #prevents blank submission from create new trick
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable,  :omniauth_providers => [:facebook]

  has_many :cats

  def self.from_omniauth(auth)
      where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
        user.provider = auth.provider
        user.uid = auth.uid
        user.email = auth.info.email
        user.password = Devise.friendly_token[0,20]
      end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  #before_action :authenticate_user!

  def index
  end

end

app/controllers/callbacks_controller.rb
class CallbacksController < Devise::OmniauthCallbacksController
  def facebook
    @user = User.from_omniauth(request.env["omniauth.auth"])

    sign_in_and_redirect @user
  end
end

app/controllers/cat_tricks_controller.rb
class CatTricksController < ApplicationController
  before_action :current_cat_trick, only: [:edit, :update]
    before_action :current_cat, only: [:edit, :update]

  def edit
    @cat = Cat.find_by_id(@cat_trick.cat_id)
    @trick = Trick.find_by_id(@cat_trick.trick_id)
  end

  def update
    @cat = Cat.find_by_id(@cat_trick.cat_id)
    @cat_trick.update (cat_trick_params)
    redirect_to cat_path(@cat)
  end

  private
    def cat_trick_params
      params.require(:cat_trick).permit(:rating)
    end

    def current_cat_trick
      @cat_trick = CatTrick.find_by_id(params[:id])
    end

    def current_cat
      @cat = Cat.find_by_id(params[:id])
    end

end

app/controllers/cats_controller.rb
class CatsController < ApplicationController
  before_action :current_cat, only: [:edit, :show, :update, :destroy]

  def index
    @cats = current_user.cats
    render json: @cats
  end

  def indexes
    indexes = Cat.indexes(current_user)
    render json: indexes
  end

  def new
    @cat = Cat.new
  end

  def create
    @cat = Cat.new(cat_params)
    @cat.user_id = current_user.id if current_user
    if @cat.save
      redirect_to cat_path(@cat)
    else
      flash[:notice] = "Please name your cat"
      render :new
    end
  end

  def update
    if @cat.update (cat_params)
      redirect_to cat_path(@cat)
    else
      render :edit
    end
  end

  def show
    @comment = @cat.comment.build
    @cat = Cat.find(params[:id])
    respond_to do |format|
      format.html { render :show }
      format.json { render json: @cat }
    end
  end

  def edit
  end

  def destroy
    @cat.delete
    redirect_to root_path, notice: "#{@cat.name} was deleted"
  end

  def most_talented
    @cats = Cat.most_talented
  end

  private
    def cat_params
      params.require(:cat).permit(:name, :color, trick_ids:[], tricks_attributes: [:name, :description])
    end

    def current_cat
      @cat = Cat.find_by_id(params[:id])
    end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_cat

  def index
    @cat = Cat.find_by(id: params[:cat_id])
  end

  def new
    @comment = Comment.new(cat_id: params[:cat_id])
  end

  def create
    @comment = @cat.comment.build(comment_params)
    if @comment.save
      render json: @comment
    else
      render cat_path
    end
  end

  private
    def comment_params
      params.require(:comment).permit(:body, :cat_id)
    end

    def set_cat
      @cat = Cat.find(params[:cat_id])
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def create
    @user = User.find_or_create_by(uid: auth['uid']) do |u|
      u.name = auth['info']['name']
      u.email = auth['info']['email']
      u.image = auth['info']['image']
    end

    session[:user_id] = @user.id

    render 'users#show'
  end


  private
    def auth
      request.env['omniauth.auth']
    end

end

app/controllers/tricks_controller.rb
class TricksController < ApplicationController
  before_action :current_cat

  def new
    @trick = Trick.new(cat_ids: params[:cat_id])
  end

  def index
    @tricks = Trick.all
  end

  def create
    @cat = Cat.find_by(id: params[:trick][:cat_ids])
    @trick = Trick.new(trick_params)
    if @trick.save
      redirect_to cat_trick_path(@cat, @trick)
    else
      render :new
    end
  end

  def show
    @trick = Trick.find_by_id(params[:id])
  end

  private

    def trick_params
      params.require(:trick).permit(:name, :cat_ids)
    end

    def current_cat
      @cat = Cat.find_by_id(params[:cat_id])
    end



end

app/controllers/user_controller.rb
class UserController < ApplicationController

  def show
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_user.html.erb
<div>
  Hi, <%= current_user.email %>!
</div>

<% if flash[:notice] %>
  <div class="notice">
    <%= flash[:notice] %>
    <%= flash[:notice] = nil %>
  </div>
<% end %>

<br />

<h5>Your Cats</h5>

<div>
  <% if current_user.cats.count > 0 %>
    <ul id="cat_list"></ul>
  <% else %>
    You have no cats yet.
  <% end %>
</div>

<%= link_to "Add a New Cat", new_cat_path %>

app/views/application/index.html.erb
<h3>Welcome to Cat Tricks</h3>

<% if current_user %>

  <%= render 'user' %>

<% else %>

  <div>
    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras eget metus mi. Curabitur mauris justo, porta vitae molestie sed, rhoncus et urna. Curabitur vulputate pellentesque dolor, ac vehicula velit consequat eu. Pellentesque dignissim tempus maximus. Pellentesque venenatis condimentum iaculis. Donec imperdiet scelerisque arcu laoreet pulvinar. Aenean enim nisl, posuere ac nibh sit amet, tempor consectetur nisl. Cras in augue diam. Sed sed est commodo, scelerisque neque a, viverra enim. Nullam sit amet volutpat sem. Proin at mattis dolor.
  </div>

<% end %>

app/views/cat_tricks/edit.html.erb
<h3><%= @cat.name %>'s Progress Rating for <%= @trick.name %></h3>

<p>Rate progress on a scale of 1 (beginner) to 5 (expert).</p>

<%= form_for @cat_trick do |f| %>

<div class="field">
  <%= f.label :rating, 'Rating:' %>
  <%= f.number_field :rating, min: 1, max: 5 %>
</div>

<div class="actions">
  <%= f.submit "Update cat's progress" %>
</div>


<% end %>

app/views/cats/_cat.html.erb
<a href="#" class="js-previous" data-id="<%= @cat.id %>">Previous Cat</a> &#124; <a href="#" class="js-next" data-id="<%= @cat.id %>">Next Cat</a>
<h2 class="cat-name"><%= @cat.name %></h2>

<p>Color: <span class="cat-color"><%= @cat.color %></p>

<div>
  <ul class="trick-list">
    <% @cat.cat_tricks.each_with_index do |trick, i| %>
      <li><%= link_to Trick.find_by_id(trick.trick_id).name, trick_path(trick.trick_id) %></li>
    <% end %>
  </ul>
</div>

app/views/cats/_comments.html.erb
<div>
  <strong>Comments</strong>
  <ul class="cat-comments">
    <% @cat.comment.each_with_index do |comment, i| %>
      <li><%= comment.body %></li>
    <% end %>
  </ul>
</div>

<div id="comment-error"></div>

<% if current_user == @cat.user %>
  <%= form_for([@cat, @comment]) do |f| %>
    <%= f.hidden_field :cat_id, :value => @cat.id %>
    <%= f.text_area :body %>
    <br />
    <%= submit_tag "Add Comment", data: { disable_with: false }%>
  <% end %>
<% end %>

app/views/cats/_form.html.erb
<% if flash[:notice] %>
  <div class="notice">
    <%= flash[:notice] %></p>
  </div>
<% end %>

<%= form_for cat do |f| %>

<div class="field">
  <%= f.label :name, 'Name:' %>
  <%= f.text_field :name %>
</div>

<br>

<div class="field">
  <%= f.label :color, 'Color:' %>
  <%= f.text_field :color %>
</div>

<br>

<div class="field">
  Select Trick(s):<br>
  <%= f.collection_check_boxes :trick_ids, Trick.all, :id, :name %>
</div>

<br>

<div class="field">
  Add a New Trick:<br>
  <%= f.fields_for :tricks, cat.tricks.build do |trick_fields| %>
    <%= trick_fields.text_field :name %>
    <%= trick_fields.text_field :description %>
  <% end %>
</div>

<br>

<div class="actions">
  <%= f.submit %>
</div>

<% end %>

app/views/cats/edit.html.erb
<%= render partial: 'form', locals: {cat: @cat} %>

app/views/cats/index.html.erb
<h1>Cat Rankings</h1>

<p>Power rankings by trick count!</p>

<ol>
  <% @cats.each do |cat| %>
    <li>
      <% if cat.user == current_user %>
       <%= link_to cat.name, cat_path(cat) %>
      <% else %>
        <%= cat.name %>
      <% end %>
      &mdash; <%= cat.cat_tricks.count %>
    </li>
  <% end %>
</ol>

app/views/cats/most_talented.html.erb
<h1>Cat Rankings</h1>

<p>Power rankings by trick count!</p>

<ol>
  <% @cats.each do |cat| %>
    <li>
      <% if cat.user == current_user %>
       <%= link_to cat.name, cat_path(cat) %>
      <% else %>
        <%= cat.name %>
      <% end %>
      &mdash; <%= cat.cat_tricks.count %>
    </li>
  <% end %>
</ol>

app/views/cats/new.html.erb
<h5>Add a Cat</h5>

<%= render partial: 'form', locals: {cat: @cat} %>

app/views/cats/show.html.erb
<%= render partial: 'cat', locals: {cat: @cat} %>

<hr />

<%= render partial: 'comments', locals: {cat: @cat} %>


<hr />

<p>
  <% if current_user == @cat.user %>
     <%= link_to "Edit Cat's Details", edit_cat_path(@cat) %>
     <br /><br />
     <%= link_to "Delete Cat", cat_path(@cat), method: :delete, data: {confirm: "Are you sure?"} %>
  <% end %>
</p>

app/views/comments/_form.html.erb
<% if flash[:notice] %>
  <div class="notice">
    <%= flash[:notice] %>
    <%= flash[:notice] = nil %>
  </div>
<% end %>

<%= form_for([@comment.cat, @comment]) do |f| %>
  <%= f.hidden_field :cat_id %>

  <div class="field">
    <%= f.label :body, 'Comment:' %>
    <%= f.text_field :body %>
  </div>

  <br>

  <div>
    <%= f.submit %>
  </div>

<% end %>

app/views/comments/index.html.erb
<h2>All Comments for <%= @cat.name %></h2>

<div>
  <% @cat.comment.each do |comment| %>
    <div class="cat_comment">
      <%= comment.created_at.strftime("%B %-d, %Y") %><br /><%= comment.body %>
    </div>
  <% end %>
</div>

<%= link_to "Add Comment", new_cat_comment_path(@cat) %>
<br />
<%= link_to "Back to Cat's Main Page", cat_path(@cat) %>

app/views/layouts/_header.html.erb
<nav class="nav">
  <%= link_to "Home", root_path %> &#124;
  <% if !current_user %>
    <%= link_to "Sign Up", new_user_registration_path %> &#124;
    <%= link_to "Sign In", new_user_session_path %>
  <% else %>
    <%= link_to "Sign Out", destroy_user_session_path, method: :delete %> &#124;
    <%= link_to "Cat Rankings", cats_most_talented_path %>
  <% end %>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CatTricks</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= render 'layouts/header' %>

    <%= yield %>
  </body>
</html>

app/views/tricks/_form.html.erb
<%= form_for trick do |f| %>

  <div class="field">
    <%= f.label :name, 'Name:' %>
    <%= f.text_field :name %>
  </div>

  <br>

  <div class="field">
    <%= f.label :description, 'Description:' %>
    <%= f.text_field :description %>
  </div>

  <div>
    <%= f.submit %>
  </div>

<% end %>

app/views/tricks/index.html.erb
<h1>Tricks</h1>

<ul>
  <% @tricks.each do |trick| %>
    <li><%= link_to trick.name, trick_path(trick) %></li>
  <% end %>
</ul>

<hr />

<br /><br />

app/views/tricks/new.html.erb
<h3>Add a New Trick</h3>

<%= render partial: 'form', locals: {trick: @trick} %>

app/views/tricks/show.html.erb
<h3><%= @trick.name %></h3>
<div>
  <%= @trick.description %>
</div>
<%= link_to "Back to cat's tricks", cat_tricks_path(@cat) %>

app/views/users/show.html.erb
<h1>User show page</h1>